package com.example.demo.model;

import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.validator.constraints.NotBlank;

public class Emp {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EMP.EMPNO
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    private Short empno;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EMP.ENAME
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    @NotBlank(message = "ename不能为空")
    private String ename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EMP.JOB
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    private String job;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EMP.MGR
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    private Short mgr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EMP.HIREDATE
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    private Date hiredate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EMP.SAL
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    private BigDecimal sal;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EMP.COMM
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    private BigDecimal comm;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column EMP.DEPTNO
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    private Short deptno;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EMP.EMPNO
     *
     * @return the value of EMP.EMPNO
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    public Short getEmpno() {
        return empno;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EMP.EMPNO
     *
     * @param empno the value for EMP.EMPNO
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    public void setEmpno(Short empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EMP.ENAME
     *
     * @return the value of EMP.ENAME
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EMP.ENAME
     *
     * @param ename the value for EMP.ENAME
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EMP.JOB
     *
     * @return the value of EMP.JOB
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EMP.JOB
     *
     * @param job the value for EMP.JOB
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EMP.MGR
     *
     * @return the value of EMP.MGR
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    public Short getMgr() {
        return mgr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EMP.MGR
     *
     * @param mgr the value for EMP.MGR
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    public void setMgr(Short mgr) {
        this.mgr = mgr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EMP.HIREDATE
     *
     * @return the value of EMP.HIREDATE
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    public Date getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EMP.HIREDATE
     *
     * @param hiredate the value for EMP.HIREDATE
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EMP.SAL
     *
     * @return the value of EMP.SAL
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    public BigDecimal getSal() {
        return sal;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EMP.SAL
     *
     * @param sal the value for EMP.SAL
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    public void setSal(BigDecimal sal) {
        this.sal = sal;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EMP.COMM
     *
     * @return the value of EMP.COMM
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    public BigDecimal getComm() {
        return comm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EMP.COMM
     *
     * @param comm the value for EMP.COMM
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    public void setComm(BigDecimal comm) {
        this.comm = comm;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column EMP.DEPTNO
     *
     * @return the value of EMP.DEPTNO
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    public Short getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column EMP.DEPTNO
     *
     * @param deptno the value for EMP.DEPTNO
     *
     * @abatorgenerated Fri Aug 13 10:24:05 CST 2021
     */
    public void setDeptno(Short deptno) {
        this.deptno = deptno;
    }
}