package com.example.demo.dao;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import org.springframework.stereotype.Repository;

import com.example.demo.model.Emp;
import com.example.demo.model.EmpExample;
import com.ibatis.sqlmap.client.SqlMapClient;

@Repository
public class EmpDaoImpl extends SqlMapClientDaoSupport implements EmpDao {

	@Autowired
	public EmpDaoImpl(SqlMapClient sqlMapClient) {
		super.setSqlMapClient(sqlMapClient);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to
	 * the database table EMP
	 *
	 * @abatorgenerated Tue Aug 17 17:07:40 CST 2021
	 */
	public void insert(Emp record) {
		getSqlMapClientTemplate().insert("EMP.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to
	 * the database table EMP
	 *
	 * @abatorgenerated Tue Aug 17 17:07:40 CST 2021
	 */
	public int updateByPrimaryKey(Emp record) {
		int rows = getSqlMapClientTemplate().update("EMP.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to
	 * the database table EMP
	 *
	 * @abatorgenerated Tue Aug 17 17:07:40 CST 2021
	 */
	public int updateByPrimaryKeySelective(Emp record) {
		int rows = getSqlMapClientTemplate().update("EMP.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to
	 * the database table EMP
	 *
	 * @abatorgenerated Tue Aug 17 17:07:40 CST 2021
	 */
	public List selectByExample(EmpExample example) {
		List list = getSqlMapClientTemplate().queryForList("EMP.abatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to
	 * the database table EMP
	 *
	 * @abatorgenerated Tue Aug 17 17:07:40 CST 2021
	 */
	public Emp selectByPrimaryKey(Short empno) {
		Emp key = new Emp();
		key.setEmpno(empno);
		Emp record = (Emp) getSqlMapClientTemplate().queryForObject("EMP.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to
	 * the database table EMP
	 *
	 * @abatorgenerated Tue Aug 17 17:07:40 CST 2021
	 */
	public int deleteByExample(EmpExample example) {
		int rows = getSqlMapClientTemplate().delete("EMP.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to
	 * the database table EMP
	 *
	 * @abatorgenerated Tue Aug 17 17:07:40 CST 2021
	 */
	public int deleteByPrimaryKey(Short empno) {
		Emp key = new Emp();
		key.setEmpno(empno);
		int rows = getSqlMapClientTemplate().delete("EMP.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to
	 * the database table EMP
	 *
	 * @abatorgenerated Tue Aug 17 17:07:40 CST 2021
	 */
	public int countByExample(EmpExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject("EMP.abatorgenerated_countByExample",
				example);
		return count.intValue();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to
	 * the database table EMP
	 *
	 * @abatorgenerated Tue Aug 17 17:07:40 CST 2021
	 */
	public int updateByExampleSelective(Emp record, EmpExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("EMP.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to
	 * the database table EMP
	 *
	 * @abatorgenerated Tue Aug 17 17:07:40 CST 2021
	 */
	public int updateByExample(Emp record, EmpExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("EMP.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the
	 * database table EMP
	 *
	 * @abatorgenerated Tue Aug 17 17:07:40 CST 2021
	 */
	private static class UpdateByExampleParms extends EmpExample {
		private Object record;

		public UpdateByExampleParms(Object record, EmpExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}